import headphone from "./assets/headphone.jpg";
export const Products = [
    {
        id:1,
        productName:"phone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:2,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:3,
        productName:"movin",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:4,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:5,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:6,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
     {
        id:7,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:8,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:9,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:10,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Electronics",
    },
    {
        id:11,
        productName:"Iphone",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Women",
    },
    {
        id:12,
        productName:"Airpods",
        Price:6000,
        productImage:headphone,
        productDescription: "this product is best  you can buy any product form our shop",
         category: "Man",
    }
]